### ISSUE TITLE
関数がreturn文で終わっていない場合にエラーが出る

### ISSUE THREAD

**Issue by tct-i15fujimura1s** [tctsigemura/C--#70]
https://github.com/tctsigemura/C--/blob/0847a1e4db075fb67b75cfb40a54be6b839ae0d9/src/parser.c#L1005
```C
int factorial(int n) {
  if(x <= 0) return 1;
  else return n * factorial(n-1);
}
```
この場合、関数は必ず値を返すにも関わらず、「関数が値を返していない」とエラーが出ます。
エラーメッセージがわかりづらいのではないでしょうか。
例えば「関数がreturn文で終わっていない」などならわかりやすくなると思います。

**Comment by tctsigemura** [comment]
そうですね．
エラーメッセージを変更しましょう．
指摘，ありがとうございました．

**Comment by tctsigemura** [comment]
エラーメッセージを訂正しました．
